// GENERATED BY THE COMMAND ABOVE; DO NOT EDIT
// This file was generated by swaggo/swag

package docs

import (
	"bytes"
	"encoding/json"
	"strings"

	"github.com/alecthomas/template"
	"github.com/swaggo/swag"
)

var doc = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{.Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "license": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/v1/user/mobile/login": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "001 手机一键注册/登陆 2020-09-10"
                ],
                "summary": "手机一键注册/登陆 (ok)",
                "parameters": [
                    {
                        "type": "string",
                        "default": "android",
                        "description": "android",
                        "name": "User-Agent",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "default": "1.0.0",
                        "description": "版本",
                        "name": "Version",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "手机号登陆/注册 请求参数",
                        "name": "LoginParams",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/swag.LoginParamsSwag"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/swag.LoginSwag"
                        }
                    },
                    "500": {
                        "description": "{\"code\":500,\"data\":{},\"msg\":\"fail\",\"tm\":\"1588888888\"}",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/api/v1/user/wechat/login": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "002 微信注册/登陆 2020-09-11"
                ],
                "summary": "微信注册/登陆 (ok)",
                "parameters": [
                    {
                        "type": "string",
                        "default": "android",
                        "description": "android",
                        "name": "User-Agent",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "default": "1.0.0",
                        "description": "版本",
                        "name": "Version",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "微信登陆/注册 请求参数",
                        "name": "WxLoginParam",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/swag.WxLoginSwag"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/swag.LoginSwag"
                        }
                    },
                    "500": {
                        "description": "{\"code\":500,\"data\":{},\"msg\":\"fail\",\"tm\":\"1588888888\"}",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/api/v1/user/weibo/login": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "003 微博注册/登陆 2020-09-11"
                ],
                "summary": "微博注册/登陆 (ok)",
                "parameters": [
                    {
                        "type": "string",
                        "default": "android",
                        "description": "android",
                        "name": "User-Agent",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "default": "1.0.0",
                        "description": "版本",
                        "name": "Version",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "微博登陆/注册 请求参数",
                        "name": "WeiboLoginParams",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/swag.WeiboLoginSwag"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/swag.LoginSwag"
                        }
                    },
                    "500": {
                        "description": "{\"code\":500,\"data\":{},\"msg\":\"fail\",\"tm\":\"1588888888\"}",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "swag.LoginParamsSwag": {
            "type": "object",
            "required": [
                "mobileNum"
            ],
            "properties": {
                "mobileNum": {
                    "description": "手机号",
                    "type": "string",
                    "example": "手机号码"
                },
                "platform": {
                    "description": "平台",
                    "type": "integer",
                    "example": 1
                }
            }
        },
        "swag.LoginSwag": {
            "type": "object",
            "properties": {
                "token": {
                    "description": "token",
                    "type": "string"
                },
                "user": {
                    "description": "用户信息",
                    "type": "object",
                    "$ref": "#/definitions/swag.User"
                }
            }
        },
        "swag.User": {
            "type": "object",
            "properties": {
                "age": {
                    "type": "integer"
                },
                "avatar": {
                    "type": "string"
                },
                "background_img": {
                    "type": "string"
                },
                "born": {
                    "type": "string"
                },
                "channel_id": {
                    "type": "integer"
                },
                "city": {
                    "type": "string"
                },
                "create_at": {
                    "type": "integer"
                },
                "device_type": {
                    "type": "integer"
                },
                "gender": {
                    "type": "integer"
                },
                "id": {
                    "type": "integer"
                },
                "is_anchor": {
                    "type": "integer"
                },
                "last_login_time": {
                    "type": "integer"
                },
                "mobile_num": {
                    "type": "integer"
                },
                "nick_name": {
                    "type": "string"
                },
                "password": {
                    "type": "string"
                },
                "signature": {
                    "type": "string"
                },
                "status": {
                    "type": "integer"
                },
                "title": {
                    "type": "string"
                },
                "update_at": {
                    "type": "integer"
                },
                "user_id": {
                    "type": "string"
                }
            }
        },
        "swag.WeiboLoginSwag": {
            "type": "object",
            "required": [
                "access_token",
                "uid"
            ],
            "properties": {
                "access_token": {
                    "type": "string"
                },
                "uid": {
                    "type": "integer"
                }
            }
        },
        "swag.WxLoginSwag": {
            "type": "object",
            "required": [
                "code"
            ],
            "properties": {
                "code": {
                    "type": "string",
                    "example": "授权码"
                }
            }
        }
    }
}`

type swaggerInfo struct {
	Version     string
	Host        string
	BasePath    string
	Schemes     []string
	Title       string
	Description string
}

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = swaggerInfo{
	Version:     "1.0",
	Host:        "",
	BasePath:    "",
	Schemes:     []string{},
	Title:       "FPV电竞APP（登陆服）",
	Description: "### 一、公共参数说明（此栏参数均为Headers请求头传递）\n| 参数名 | 说明 | 示例 |\n| ------ | :----- | :----- |\n| User-Agent | 用户代理 | android |\n| Version | 当前版本 | 1.0.1 |\n### 二、请求体说明（此栏参数均为POST JSON传递，不可用form-data提交）\n\n{\n'mobileNum': '13177656222',\n'platform': 0\n}\n### 三、API错误码文档\n[点击查看](/api/v1/doc)\n### 四、HTTP状态码说明\n| 状态码 | 说明 |\n| ------ | :----- |\n| 200 | 操作成功 |\n| 400 | 参数错误 |\n| 500 | 内部错误 |",
}

type s struct{}

func (s *s) ReadDoc() string {
	sInfo := SwaggerInfo
	sInfo.Description = strings.Replace(sInfo.Description, "\n", "\\n", -1)

	t, err := template.New("swagger_info").Funcs(template.FuncMap{
		"marshal": func(v interface{}) string {
			a, _ := json.Marshal(v)
			return string(a)
		},
	}).Parse(doc)
	if err != nil {
		return doc
	}

	var tpl bytes.Buffer
	if err := t.Execute(&tpl, sInfo); err != nil {
		return doc
	}

	return tpl.String()
}

func init() {
	swag.Register(swag.Name, &s{})
}
