// GENERATED BY THE COMMAND ABOVE; DO NOT EDIT
// This file was generated by swaggo/swag at
// 2020-09-10 20:27:39.357445 +0800 CST m=+0.024388314

package docs

import (
	"github.com/swaggo/swag"
)

var doc = `{
    "swagger": "2.0",
    "info": {
        "description": "### API错误码文档 [点击查看](/api/v1/doc)",
        "title": "FPV电竞app(登陆服)",
        "contact": {},
        "license": {},
        "version": "1.0"
    },
    "paths": {
        "/api/v1/user/mobile/login": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "001 手机一键注册/登陆 2020-09-10"
                ],
                "summary": "手机一键注册/登陆 (ok)",
                "parameters": [
                    {
                        "type": "string",
                        "default": "android",
                        "description": "android",
                        "name": "User-Agent",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "default": "1.0.0",
                        "description": "版本",
                        "name": "Version",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "登陆/注册 请求参数",
                        "name": "LoginParams",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/swag.LoginParamsSwag"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/swag.LoginSwag"
                        }
                    },
                    "500": {
                        "description": "{\"code\":500,\"data\":{},\"msg\":\"fail\",\"tm\":\"1588888888\"}",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "swag.LoginParamsSwag": {
            "type": "object",
            "required": [
                "mobileNum"
            ],
            "properties": {
                "mobileNum": {
                    "type": "string",
                    "example": "手机号码"
                },
                "platform": {
                    "type": "integer",
                    "example": 1
                }
            }
        },
        "swag.LoginSwag": {
            "type": "object",
            "properties": {
                "token": {
                    "type": "string"
                },
                "user": {
                    "type": "object",
                    "$ref": "#/definitions/swag.User"
                }
            }
        },
        "swag.User": {
            "type": "object",
            "properties": {
                "age": {
                    "type": "integer"
                },
                "avatar": {
                    "type": "string"
                },
                "background_img": {
                    "type": "string"
                },
                "born": {
                    "type": "string"
                },
                "channel_id": {
                    "type": "integer"
                },
                "city": {
                    "type": "string"
                },
                "create_at": {
                    "type": "integer"
                },
                "device_type": {
                    "type": "integer"
                },
                "gender": {
                    "type": "integer"
                },
                "id": {
                    "type": "integer"
                },
                "is_anchor": {
                    "type": "integer"
                },
                "last_login_time": {
                    "type": "integer"
                },
                "mobile_num": {
                    "type": "integer"
                },
                "nick_name": {
                    "type": "string"
                },
                "password": {
                    "type": "string"
                },
                "signature": {
                    "type": "string"
                },
                "status": {
                    "type": "integer"
                },
                "title": {
                    "type": "string"
                },
                "update_at": {
                    "type": "integer"
                },
                "user_id": {
                    "type": "string"
                }
            }
        }
    }
}`

type s struct{}

func (s *s) ReadDoc() string {
	return doc
}
func init() {
	swag.Register(swag.Name, &s{})
}
