publicAddr: :13002
pprofAddr: :12002
mode: prod
mysql:
  main:
    master: saisai:igT0vXhruwTYHzzEYilh@tcp(10.21.33.246:15139)/sports_service?charset=utf8mb4
    slave:
      - sports_service:igT0vXhruwTYHzzEYilh@tcp(10.21.33.246:15139)/sports_service?charset=utf8mb4
      - sports_service:igT0vXhruwTYHzzEYilh@tcp(10.21.33.246:15139)/sports_service?charset=utf8mb4
      - sports_service:igT0vXhruwTYHzzEYilh@tcp(10.21.33.246:15139)/sports_service?charset=utf8mb4
    maxIdle: 128
    maxActive: 128

redis:
  main:
    master:
      ip: 10.34.16.102
      port: 6379

    slave:
      - ip: 10.34.16.102
        port: 6379

    dboption:
      - dbid: 0
        name:
        maxIdle: 128
        maxActive: 128
redisPassword: Furyqdz7JMkAGjRM
nsqAddr: 127.0.0.1:4150
fileAddr: http://192.168.50.148:13002/upload/
amqpDsn: amqp://admin:admin@127.0.0.1:5672
## 日志等级 0 debug 1 info 2 warn 3 error
log:
  path: /data/service/fpv-backend-api/log/backend_server_%s.log
  level: 0
  showColor: true

debug: true
