publicAddr: :13000
pprofAddr: :12002
mode: prod
mysql:
  main:
    master: fpv_app:ZPXWe5OjbAJmNBQk@tcp(120.92.141.106:33497)/fpv-app-api?charset=utf8mb4
    slave:
      - fpv_app:ZPXWe5OjbAJmNBQk@tcp(120.92.141.106:33497)/fpv-app-api?charset=utf8mb4
      - fpv_app:ZPXWe5OjbAJmNBQk@tcp(120.92.141.106:33497)/fpv-app-api?charset=utf8mb4
      - fpv_app:ZPXWe5OjbAJmNBQk@tcp(120.92.141.106:33497)/fpv-app-api?charset=utf8mb4
    maxIdle: 128
    maxActive: 128
  venue:
    master: venue:umgSL4PTXyn2Z9li@tcp(120.92.141.106:33497)/venue?charset=utf8mb4
    slave:
      - venue:umgSL4PTXyn2Z9li@tcp(120.92.141.106:33497)/venue?charset=utf8mb4
      - venue:umgSL4PTXyn2Z9li@tcp(120.92.141.106:33497)/venue?charset=utf8mb4
      - venue:umgSL4PTXyn2Z9li@tcp(120.92.141.106:33497)/venue?charset=utf8mb4
    maxIdle: 128
    maxActive: 128
redis:
  main:
    master:
      ip: 192.168.0.218
      port: 6379

    slave:
      - ip: 192.168.0.218
        port: 6379

    dboption:
      - dbid: 0
        name:
        maxIdle: 128
        maxActive: 128
redisPassword: o6DPVfuCAUwOgrNM
nsqAddr: 127.0.0.1:4150
fileAddr: http://192.168.50.148:13002/upload/
amqpDsn: amqp://admin:admin@127.0.0.1:5672
# 腾讯im SDKAppID
tencentImAppId: 1400576334
# 腾讯im 密钥
tencentImSecret: 080789c06a28b355e1ec94b97ad61edc4eb887275e68fa0046f5659cead396e7
# 腾讯im 管理员
tencentImIdentifier: bluetrans
## 日志等级 0 debug 1 info 2 warn 3 error
log:
  path: /data/logs/fpv-backend-api/backend_server_%s.log
  level: 0
  showColor: true

debug: true
