publicAddr: :13000
pprofAddr: :12002
mode: dev
mysql:
  main:
    master: root:bluetrans888@tcp(192.168.5.12:3306)/sports_service?charset=utf8mb4
    slave:
      - root:bluetrans888@tcp(192.168.5.12:3306)/sports_service?charset=utf8mb4
      - root:bluetrans888@tcp(192.168.5.12:3306)/sports_service?charset=utf8mb4
      - root:bluetrans888@tcp(192.168.5.12:3306)/sports_service?charset=utf8mb4
    maxIdle: 128
    maxActive: 128

redis:
  main:
    master:
      ip: 127.0.0.1
      port: 6379

    slave:
      - ip: 127.0.0.1
        port: 6379

    dboption:
      - dbid: 0
        name:
        maxIdle: 128
        maxActive: 128
nsqAddr: 127.0.0.1:4150
fileAddr: http://192.168.50.148:13002/upload/
amqpDsn: amqp://admin:admin@127.0.0.1:5672
## 日志等级 0 debug 1 info 2 warn 3 error
log:
  path: /data/service/fpv-backend-api/log/backend_server_%s.log
  level: 0
  showColor: true

debug: true
