publicAddr: :13002
pprofAddr: :12002
mode: dev
mysql:
  main:
    master: root:aa3202381@tcp(127.0.0.1:3306)/fpv2?charset=utf8mb4
    slave:
      - root:aa3202381@tcp(127.0.0.1:3306)/fpv2?charset=utf8mb4
      - root:aa3202381@tcp(127.0.0.1:3306)/fpv2?charset=utf8mb4
      - root:aa3202381@tcp(127.0.0.1:3306)/fpv2?charset=utf8mb4
    maxIdle: 128
    maxActive: 128

redis:
  main:
    master:
      ip: 128.0.0.1
      port: 6379

    slave:
      - ip: 128.0.0.1
        port: 6379

    dboption:
      - dbid: 0
        name:
        maxIdle: 128
        maxActive: 128

## 日志等级 0 debug 1 info 2 warn 3 error
log:
  path: ./log/backend_server.log
  level: 0
  showColor: true

debug: true
