publicAddr: :13000
pprofAddr: :12002
mode: prod
mysql:
  main:
    master: root:123456@tcp(127.0.0.1:3306)/sports_service?charset=utf8mb4
    slave:
      - root:123456@tcp(127.0.0.1:3306)/sports_service?charset=utf8mb4
      - root:123456@tcp(127.0.0.1:3306)/sports_service?charset=utf8mb4
      - root:123456@tcp(127.0.0.1:3306)/sports_service?charset=utf8mb4
    maxIdle: 128
    maxActive: 128
    logPath: /data/logs/fpv-backend-api/db/db_fpv_%s.log
  venue:
    master: root:123456@tcp(127.0.0.1:3306)/venue?charset=utf8mb4
    slave:
      - root:123456@tcp(127.0.0.1:3306)/venue?charset=utf8mb4
      - root:123456@tcp(127.0.0.1:3306)/venue?charset=utf8mb4
      - root:123456@tcp(127.0.0.1:3306)/venue?charset=utf8mb4
    maxIdle: 128
    maxActive: 128
    logPath: /data/logs/fpv-backend-api/db/db_venue_%s.log

redis:
  main:
    master:
      ip: 127.0.0.1
      port: 6378

    slave:
      - ip: 127.0.0.1
        port: 6378

    dboption:
      - dbid: 0
        name:
        maxIdle: 128
        maxActive: 128
redisPassword: yN1MnL8O7DfS3aBh
nsqAddr: 127.0.0.1:4150
fileAddr: http://127.0.0.1:13002/upload/
amqpDsn: amqp://admin:admin@127.0.0.1:5672
# 腾讯im SDKAppID
tencentImAppId: 123456
# 腾讯im 密钥
tencentImSecret: 123456
# 腾讯im 管理员
tencentImIdentifier: admin
## 日志等级 0 debug 1 info 2 warn 3 error
log:
  path: /data/logs/fpv-backend-api/backend_server_%s.log
  level: 0
  showColor: true

debug: true
