stages:
  - build
  - test
variables:
  server_ips: 192.168.5.12
  build_shell: 'GOOS=linux GOARCH=amd64 go build -o ${project_dir}${project_name} ${project_dir}/main.go'
  rsync_shell: 'server_ips=${server_ips}; ips=($${server_ips//,/ }); for ip in $$ips; do rsync -avzP  --exclude="*.go" ${project_dir}${project_name} ${project_dir}${project_name}.service ${project_dir}config gitlab-pusher@$$ip::${project_name};done'
build-job-fpv:
  variables:
    project_name: fpv-app-api
    project_dir: ./app/
  tags:
    - gitlab_build_theseus
  stage: build
  only:
    - develop
  script:
    - 'eval $build_shell'
    - 'eval $rsync_shell'
build-job-backend:
  variables:
    project_name: fpv-backend-api
    project_dir: ./backend/
  tags:
    - gitlab_build_theseus
  stage: build
  only:
    - develop
  script:
    - 'eval $build_shell'
    - 'eval $rsync_shell'