stages:
  - build
  - test
build-job-api:
  tags:
    - gitlab_build_theseus
  stage: build
  only:
    - tags
  script:
    - GOOS=linux GOARCH=amd64 go build -o ./app/fpv-app-api ./app/main.go
    - rsync -avz --port=52873  --password-file=/home/gitlab-runner/client.pass ./app/fpv-app-api  gitlab-pusher@120.92.172.80::fpv-app-api
