// GENERATED BY THE COMMAND ABOVE; DO NOT EDIT
// This file was generated by swaggo/swag at
// 2020-09-10 19:17:43.749748 +0800 CST m=+0.139992816

package docs

import (
	"github.com/swaggo/swag"
)

var doc = `{
    "swagger": "2.0",
    "info": {
        "description": "| 400 | 参数错误 |",
        "title": "FPV电竞app(应用服)",
        "contact": {},
        "license": {},
        "version": "1.0"
    },
    "paths": {}
}`

type s struct{}

func (s *s) ReadDoc() string {
	return doc
}
func init() {
	swag.Register(swag.Name, &s{})
}
