// GENERATED BY THE COMMAND ABOVE; DO NOT EDIT
// This file was generated by swaggo/swag

package docs

import (
	"bytes"
	"encoding/json"
	"strings"

	"github.com/alecthomas/template"
	"github.com/swaggo/swag"
)

var doc = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{.Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "license": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/v1/attention/cancel": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "关注模块"
                ],
                "summary": "取消关注 (ok)",
                "parameters": [
                    {
                        "type": "string",
                        "description": "AppId",
                        "name": "AppId",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "调用/api/v1/client/init接口 服务端下发的secret",
                        "name": "Secret",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "请求时间戳 单位：秒",
                        "name": "Timestamp",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "签名 md5签名32位值",
                        "name": "Sign",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "default": "1.0.0",
                        "description": "版本",
                        "name": "Version",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "取消关注请求参数",
                        "name": "CancelAttentionParam",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/mattention.CancelAttentionParam"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"code\":200,\"data\":{},\"msg\":\"success\",\"tm\":\"1588888888\"}",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "{\"code\":500,\"data\":{},\"msg\":\"fail\",\"tm\":\"1588888888\"}",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/api/v1/attention/list": {
            "get": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "关注模块"
                ],
                "summary": "关注的用户列表[分页获取] (ok)",
                "parameters": [
                    {
                        "type": "string",
                        "description": "AppId",
                        "name": "AppId",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "调用/api/v1/client/init接口 服务端下发的secret",
                        "name": "Secret",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "请求时间戳 单位：秒",
                        "name": "Timestamp",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "签名 md5签名32位值",
                        "name": "Sign",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "default": "1.0.0",
                        "description": "版本",
                        "name": "Version",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "页码 从1开始",
                        "name": "page",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "每页展示多少 最多50条",
                        "name": "size",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/muser.UserInfoResp"
                            }
                        }
                    },
                    "500": {
                        "description": "{\"code\":500,\"data\":{},\"msg\":\"fail\",\"tm\":\"1588888888\"}",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/api/v1/attention/user": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "关注模块"
                ],
                "summary": "关注用户 (ok)",
                "parameters": [
                    {
                        "type": "string",
                        "description": "AppId",
                        "name": "AppId",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "调用/api/v1/client/init接口 服务端下发的secret",
                        "name": "Secret",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "请求时间戳 单位：秒",
                        "name": "Timestamp",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "签名 md5签名32位值",
                        "name": "Sign",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "default": "1.0.0",
                        "description": "版本",
                        "name": "Version",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "关注用户请求参数",
                        "name": "AddAttentionParam",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/mattention.AddAttentionParam"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"code\":200,\"data\":{},\"msg\":\"success\",\"tm\":\"1588888888\"}",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "{\"code\":500,\"data\":{},\"msg\":\"fail\",\"tm\":\"1588888888\"}",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/api/v1/client/init": {
            "get": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "通用接口接口"
                ],
                "summary": "初始化接口 (ok)",
                "parameters": [
                    {
                        "type": "string",
                        "default": "android",
                        "description": "AppId",
                        "name": "AppId",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "请求时间戳 单位：秒",
                        "name": "Timestamp",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "签名 md5签名32位值",
                        "name": "Sign",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "default": "1.0.0",
                        "description": "版本",
                        "name": "Version",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"code\":200,\"data\":{\"secret\": \"DnaukFwVILpcewX6\"},\"msg\":\"success\",\"tm\":\"1588888888\"}",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "{\"code\":500,\"data\":{},\"msg\":\"fail\",\"tm\":\"1588888888\"}",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/api/v1/collect/delete": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "收藏模块"
                ],
                "summary": "删除收藏的历史记录 (ok)",
                "parameters": [
                    {
                        "type": "string",
                        "description": "AppId",
                        "name": "AppId",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "调用/api/v1/client/init接口 服务端下发的secret",
                        "name": "Secret",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "请求时间戳 单位：秒",
                        "name": "Timestamp",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "签名 md5签名32位值",
                        "name": "Sign",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "default": "1.0.0",
                        "description": "版本",
                        "name": "Version",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "删除收藏记录 请求参数",
                        "name": "DeleteCollectParam",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/mcollect.DeleteCollectParam"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"code\":200,\"data\":{},\"msg\":\"success\",\"tm\":\"1588888888\"}",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "{\"code\":500,\"data\":{},\"msg\":\"fail\",\"tm\":\"1588888888\"}",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/api/v1/collect/video": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "收藏模块"
                ],
                "summary": "收藏视频 (ok)",
                "parameters": [
                    {
                        "type": "string",
                        "description": "AppId",
                        "name": "AppId",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "调用/api/v1/client/init接口 服务端下发的secret",
                        "name": "Secret",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "请求时间戳 单位：秒",
                        "name": "Timestamp",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "签名 md5签名32位值",
                        "name": "Sign",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "default": "1.0.0",
                        "description": "版本",
                        "name": "Version",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "收藏视频请求参数",
                        "name": "AddCollectParam",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/mcollect.AddCollectParam"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"code\":200,\"data\":{},\"msg\":\"success\",\"tm\":\"1588888888\"}",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "{\"code\":500,\"data\":{},\"msg\":\"fail\",\"tm\":\"1588888888\"}",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/api/v1/collect/video/cancel": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "收藏模块"
                ],
                "summary": "取消收藏 (ok)",
                "parameters": [
                    {
                        "type": "string",
                        "description": "AppId",
                        "name": "AppId",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "调用/api/v1/client/init接口 服务端下发的secret",
                        "name": "Secret",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "请求时间戳 单位：秒",
                        "name": "Timestamp",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "签名 md5签名32位值",
                        "name": "Sign",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "default": "1.0.0",
                        "description": "版本",
                        "name": "Version",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "取消视频收藏请求参数",
                        "name": "CancelCollectParam",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/mcollect.CancelCollectParam"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"code\":200,\"data\":{},\"msg\":\"success\",\"tm\":\"1588888888\"}",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "{\"code\":500,\"data\":{},\"msg\":\"fail\",\"tm\":\"1588888888\"}",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/api/v1/collect/video/list": {
            "get": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "收藏模块"
                ],
                "summary": "用户收藏的视频列表[分页获取] (ok)",
                "parameters": [
                    {
                        "type": "string",
                        "description": "AppId",
                        "name": "AppId",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "调用/api/v1/client/init接口 服务端下发的secret",
                        "name": "Secret",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "请求时间戳 单位：秒",
                        "name": "Timestamp",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "签名 md5签名32位值",
                        "name": "Sign",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "default": "1.0.0",
                        "description": "版本",
                        "name": "Version",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "页码 从1开始",
                        "name": "page",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "每页展示多少 最多50条",
                        "name": "size",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/mvideo.VideosInfoResp"
                            }
                        }
                    },
                    "500": {
                        "description": "{\"code\":500,\"data\":{},\"msg\":\"fail\",\"tm\":\"1588888888\"}",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/api/v1/fans/list": {
            "get": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "关注模块"
                ],
                "summary": "用户的粉丝列表[分页获取] (ok)",
                "parameters": [
                    {
                        "type": "string",
                        "description": "AppId",
                        "name": "AppId",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "调用/api/v1/client/init接口 服务端下发的secret",
                        "name": "Secret",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "请求时间戳 单位：秒",
                        "name": "Timestamp",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "签名 md5签名32位值",
                        "name": "Sign",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "default": "1.0.0",
                        "description": "版本",
                        "name": "Version",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "页码 从1开始",
                        "name": "page",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "每页展示多少 最多50条",
                        "name": "size",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/muser.UserInfoResp"
                            }
                        }
                    },
                    "500": {
                        "description": "{\"code\":500,\"data\":{},\"msg\":\"fail\",\"tm\":\"1588888888\"}",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/api/v1/like/video": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "点赞模块"
                ],
                "summary": "视频点赞 (ok)",
                "parameters": [
                    {
                        "type": "string",
                        "description": "AppId",
                        "name": "AppId",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "调用/api/v1/client/init接口 服务端下发的secret",
                        "name": "Secret",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "请求时间戳 单位：秒",
                        "name": "Timestamp",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "签名 md5签名32位值",
                        "name": "Sign",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "default": "1.0.0",
                        "description": "版本",
                        "name": "Version",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "点赞视频请求参数",
                        "name": "GiveLikeParam",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/mlike.GiveLikeParam"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"code\":200,\"data\":{},\"msg\":\"success\",\"tm\":\"1588888888\"}",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "{\"code\":500,\"data\":{},\"msg\":\"fail\",\"tm\":\"1588888888\"}",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/api/v1/like/video/cancel": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "点赞模块"
                ],
                "summary": "取消视频点赞 (ok)",
                "parameters": [
                    {
                        "type": "string",
                        "description": "AppId",
                        "name": "AppId",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "调用/api/v1/client/init接口 服务端下发的secret",
                        "name": "Secret",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "请求时间戳 单位：秒",
                        "name": "Timestamp",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "签名 md5签名32位值",
                        "name": "Sign",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "default": "1.0.0",
                        "description": "版本",
                        "name": "Version",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "取消视频点赞请求参数",
                        "name": "CancelLikeParam",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/mlike.CancelLikeParam"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"code\":200,\"data\":{},\"msg\":\"success\",\"tm\":\"1588888888\"}",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "{\"code\":500,\"data\":{},\"msg\":\"fail\",\"tm\":\"1588888888\"}",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/api/v1/like/video/list": {
            "get": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "点赞模块"
                ],
                "summary": "用户点赞的视频列表[分页获取] (ok)",
                "parameters": [
                    {
                        "type": "string",
                        "description": "AppId",
                        "name": "AppId",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "调用/api/v1/client/init接口 服务端下发的secret",
                        "name": "Secret",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "请求时间戳 单位：秒",
                        "name": "Timestamp",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "签名 md5签名32位值",
                        "name": "Sign",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "default": "1.0.0",
                        "description": "版本",
                        "name": "Version",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "页码 从1开始",
                        "name": "page",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "每页展示多少 最多50条",
                        "name": "size",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/mvideo.VideosInfoResp"
                            }
                        }
                    },
                    "500": {
                        "description": "{\"code\":500,\"data\":{},\"msg\":\"fail\",\"tm\":\"1588888888\"}",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/api/v1/notify/setting": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "通知模块"
                ],
                "summary": "系统通知设置 (ok)",
                "parameters": [
                    {
                        "type": "string",
                        "description": "AppId",
                        "name": "AppId",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "调用/api/v1/client/init接口 服务端下发的secret",
                        "name": "Secret",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "请求时间戳 单位：秒",
                        "name": "Timestamp",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "签名 md5签名32位值",
                        "name": "Sign",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "default": "1.0.0",
                        "description": "版本",
                        "name": "Version",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "系统通知设置 请求参数",
                        "name": "NotifySettingParams",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/mnotify.NotifySettingParams"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"code\":200,\"data\":{},\"msg\":\"success\",\"tm\":\"1588888888\"}",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "{\"code\":500,\"data\":{},\"msg\":\"fail\",\"tm\":\"1588888888\"}",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/api/v1/user/edit/info": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "账号体系"
                ],
                "summary": "编辑用户信息 (ok)",
                "parameters": [
                    {
                        "type": "string",
                        "description": "AppId",
                        "name": "AppId",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "调用/api/v1/client/init接口 服务端下发的secret",
                        "name": "Secret",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "请求时间戳 单位：秒",
                        "name": "Timestamp",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "签名 md5签名32位值",
                        "name": "Sign",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "default": "1.0.0",
                        "description": "版本",
                        "name": "Version",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "编辑用户信息请求参数",
                        "name": "EditUserInfoParams",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/muser.EditUserInfoParams"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"code\":200,\"data\":{},\"msg\":\"success\",\"tm\":\"1588888888\"}",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "{\"code\":500,\"data\":{},\"msg\":\"fail\",\"tm\":\"1588888888\"}",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/api/v1/user/feedback": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "账号体系"
                ],
                "summary": "用户反馈问题 (ok)",
                "parameters": [
                    {
                        "type": "string",
                        "description": "AppId",
                        "name": "AppId",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "调用/api/v1/client/init接口 服务端下发的secret",
                        "name": "Secret",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "请求时间戳 单位：秒",
                        "name": "Timestamp",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "签名 md5签名32位值",
                        "name": "Sign",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "default": "1.0.0",
                        "description": "版本",
                        "name": "Version",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "用户反馈问题 请求参数",
                        "name": "FeedbackParam",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/muser.FeedbackParam"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"code\":200,\"data\":{},\"msg\":\"success\",\"tm\":\"1588888888\"}",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "{\"code\":500,\"data\":{},\"msg\":\"fail\",\"tm\":\"1588888888\"}",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/api/v1/user/info": {
            "get": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "账号体系"
                ],
                "summary": "用户信息 (ok)",
                "parameters": [
                    {
                        "type": "string",
                        "description": "AppId",
                        "name": "AppId",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "调用/api/v1/client/init接口 服务端下发的secret",
                        "name": "Secret",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "请求时间戳 单位：秒",
                        "name": "Timestamp",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "签名 md5签名32位值",
                        "name": "Sign",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "default": "1.0.0",
                        "description": "版本",
                        "name": "Version",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/muser.UserInfoResp"
                        }
                    },
                    "500": {
                        "description": "{\"code\":500,\"data\":{},\"msg\":\"fail\",\"tm\":\"1588888888\"}",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/api/v1/user/mobile/login": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "账号体系"
                ],
                "summary": "手机一键注册/登陆 (ok)",
                "parameters": [
                    {
                        "type": "string",
                        "description": "AppId",
                        "name": "AppId",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "调用/api/v1/client/init接口 服务端下发的secret",
                        "name": "Secret",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "请求时间戳 单位：秒",
                        "name": "Timestamp",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "签名 md5签名32位值",
                        "name": "Sign",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "default": "1.0.0",
                        "description": "版本",
                        "name": "Version",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "手机号登陆/注册 请求参数",
                        "name": "LoginParams",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/muser.LoginParams"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/swag.LoginSwag"
                        }
                    },
                    "500": {
                        "description": "{\"code\":500,\"data\":{},\"msg\":\"fail\",\"tm\":\"1588888888\"}",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/api/v1/user/qq/login": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "账号体系"
                ],
                "summary": "QQ注册/登陆 (ok)",
                "parameters": [
                    {
                        "type": "string",
                        "description": "AppId",
                        "name": "AppId",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "调用/api/v1/client/init接口 服务端下发的secret",
                        "name": "Secret",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "请求时间戳 单位：秒",
                        "name": "Timestamp",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "签名 md5签名32位值",
                        "name": "Sign",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "default": "1.0.0",
                        "description": "版本",
                        "name": "Version",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "QQ登陆/注册 请求参数",
                        "name": "WeiboLoginParams",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/muser.QQLoginParams"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/swag.LoginSwag"
                        }
                    },
                    "500": {
                        "description": "{\"code\":500,\"data\":{},\"msg\":\"fail\",\"tm\":\"1588888888\"}",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/api/v1/user/wechat/login": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "账号体系"
                ],
                "summary": "微信注册/登陆 (ok)",
                "parameters": [
                    {
                        "type": "string",
                        "description": "AppId",
                        "name": "AppId",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "调用/api/v1/client/init接口 服务端下发的secret",
                        "name": "Secret",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "请求时间戳 单位：秒",
                        "name": "Timestamp",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "签名 md5签名32位值",
                        "name": "Sign",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "default": "1.0.0",
                        "description": "版本",
                        "name": "Version",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "微信登陆/注册 请求参数",
                        "name": "WxLoginParam",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/muser.WxLoginParam"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/swag.LoginSwag"
                        }
                    },
                    "500": {
                        "description": "{\"code\":500,\"data\":{},\"msg\":\"fail\",\"tm\":\"1588888888\"}",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/api/v1/user/weibo/login": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "账号体系"
                ],
                "summary": "微博注册/登陆 (ok)",
                "parameters": [
                    {
                        "type": "string",
                        "description": "AppId",
                        "name": "AppId",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "调用/api/v1/client/init接口 服务端下发的secret",
                        "name": "Secret",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "请求时间戳 单位：秒",
                        "name": "Timestamp",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "签名 md5签名32位值",
                        "name": "Sign",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "default": "1.0.0",
                        "description": "版本",
                        "name": "Version",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "微博登陆/注册 请求参数",
                        "name": "WeiboLoginParams",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/muser.WeiboLoginParams"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/swag.LoginSwag"
                        }
                    },
                    "500": {
                        "description": "{\"code\":500,\"data\":{},\"msg\":\"fail\",\"tm\":\"1588888888\"}",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/api/v1/video/browse/history": {
            "get": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "视频模块"
                ],
                "summary": "用户浏览过的视频记录[分页获取] (ok)",
                "parameters": [
                    {
                        "type": "string",
                        "description": "AppId",
                        "name": "AppId",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "调用/api/v1/client/init接口 服务端下发的secret",
                        "name": "Secret",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "请求时间戳 单位：秒",
                        "name": "Timestamp",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "签名 md5签名32位值",
                        "name": "Sign",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "default": "1.0.0",
                        "description": "版本",
                        "name": "Version",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "页码 从1开始",
                        "name": "page",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "每页展示多少 最多50条",
                        "name": "size",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/mvideo.VideosInfoResp"
                            }
                        }
                    },
                    "500": {
                        "description": "{\"code\":500,\"data\":{},\"msg\":\"fail\",\"tm\":\"1588888888\"}",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/api/v1/video/delete/history": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "视频模块"
                ],
                "summary": "删除浏览的历史记录 (ok)",
                "parameters": [
                    {
                        "type": "string",
                        "description": "AppId",
                        "name": "AppId",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "调用/api/v1/client/init接口 服务端下发的secret",
                        "name": "Secret",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "请求时间戳 单位：秒",
                        "name": "Timestamp",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "签名 md5签名32位值",
                        "name": "Sign",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "default": "1.0.0",
                        "description": "版本",
                        "name": "Version",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "删除浏览历史记录 请求参数",
                        "name": "DeleteHistoryParam",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/mvideo.DeleteHistoryParam"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"code\":200,\"data\":{},\"msg\":\"success\",\"tm\":\"1588888888\"}",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "{\"code\":500,\"data\":{},\"msg\":\"fail\",\"tm\":\"1588888888\"}",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/api/v1/video/delete/publish": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "视频模块"
                ],
                "summary": "删除发布的视频 (ok)",
                "parameters": [
                    {
                        "type": "string",
                        "description": "AppId",
                        "name": "AppId",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "调用/api/v1/client/init接口 服务端下发的secret",
                        "name": "Secret",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "请求时间戳 单位：秒",
                        "name": "Timestamp",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "签名 md5签名32位值",
                        "name": "Sign",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "default": "1.0.0",
                        "description": "版本",
                        "name": "Version",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "删除发布的视频 请求参数",
                        "name": "DeletePublishParam",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/mvideo.DeletePublishParam"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"code\":200,\"data\":{},\"msg\":\"success\",\"tm\":\"1588888888\"}",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "{\"code\":500,\"data\":{},\"msg\":\"fail\",\"tm\":\"1588888888\"}",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/api/v1/video/publish": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "视频模块"
                ],
                "summary": "视频发布 (ok)",
                "parameters": [
                    {
                        "type": "string",
                        "description": "AppId",
                        "name": "AppId",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "调用/api/v1/client/init接口 服务端下发的secret",
                        "name": "Secret",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "请求时间戳 单位：秒",
                        "name": "Timestamp",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "签名 md5签名32位值",
                        "name": "Sign",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "default": "1.0.0",
                        "description": "版本",
                        "name": "Version",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "发布视频请求参数",
                        "name": "VideoPublishParams",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/mvideo.VideoPublishParams"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"code\":200,\"data\":{},\"msg\":\"success\",\"tm\":\"1588888888\"}",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "{\"code\":500,\"data\":{},\"msg\":\"fail\",\"tm\":\"1588888888\"}",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/api/v1/video/publish/list": {
            "get": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "视频模块"
                ],
                "summary": "用户发布的视频记录[分页获取] (ok)",
                "parameters": [
                    {
                        "type": "string",
                        "description": "AppId",
                        "name": "AppId",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "调用/api/v1/client/init接口 服务端下发的secret",
                        "name": "Secret",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "请求时间戳 单位：秒",
                        "name": "Timestamp",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "签名 md5签名32位值",
                        "name": "Sign",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "default": "1.0.0",
                        "description": "版本",
                        "name": "Version",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "页码 从1开始",
                        "name": "page",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "每页展示多少 最多50条",
                        "name": "size",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "status 状态 -1 查询全部 0 审核中 1 已发布 2 不通过",
                        "name": "status",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "条件 -1 默认时间排序 0 播放数 1 弹幕数 2 评论数 3 点赞数 4 分享数",
                        "name": "condition",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/mvideo.PublishVideosInfo"
                            }
                        }
                    },
                    "500": {
                        "description": "{\"code\":500,\"data\":{},\"msg\":\"fail\",\"tm\":\"1588888888\"}",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "mattention.AddAttentionParam": {
            "type": "object",
            "required": [
                "userId"
            ],
            "properties": {
                "userId": {
                    "type": "string",
                    "example": "需关注的用户id"
                }
            }
        },
        "mattention.CancelAttentionParam": {
            "type": "object",
            "required": [
                "userId"
            ],
            "properties": {
                "userId": {
                    "type": "string",
                    "example": "被取消关注的用户id"
                }
            }
        },
        "mcollect.AddCollectParam": {
            "type": "object",
            "required": [
                "videoId"
            ],
            "properties": {
                "videoId": {
                    "type": "integer",
                    "example": 10001
                }
            }
        },
        "mcollect.CancelCollectParam": {
            "type": "object",
            "required": [
                "videoId"
            ],
            "properties": {
                "videoId": {
                    "type": "integer",
                    "example": 10001
                }
            }
        },
        "mcollect.DeleteCollectParam": {
            "type": "object",
            "required": [
                "composeIds"
            ],
            "properties": {
                "composeIds": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                }
            }
        },
        "mlike.CancelLikeParam": {
            "type": "object",
            "required": [
                "videoId"
            ],
            "properties": {
                "videoId": {
                    "type": "integer",
                    "example": 10001
                }
            }
        },
        "mlike.GiveLikeParam": {
            "type": "object",
            "required": [
                "videoId"
            ],
            "properties": {
                "videoId": {
                    "type": "integer",
                    "example": 10001
                }
            }
        },
        "mnotify.NotifySettingParams": {
            "type": "object",
            "properties": {
                "attentionPushSet": {
                    "type": "integer"
                },
                "commentPushSet": {
                    "type": "integer"
                },
                "sharePushSet": {
                    "type": "integer"
                },
                "slotPushSet": {
                    "type": "integer"
                },
                "thumbUpPushSet": {
                    "type": "integer"
                }
            }
        },
        "muser.EditUserInfoParams": {
            "type": "object",
            "properties": {
                "avatarId": {
                    "type": "integer",
                    "example": 6
                },
                "born": {
                    "type": "string",
                    "example": "1993-06-20"
                },
                "countryId": {
                    "type": "integer",
                    "example": 1
                },
                "gender": {
                    "type": "integer",
                    "example": 1
                },
                "nickName": {
                    "type": "string",
                    "example": "陈二狗"
                },
                "signature": {
                    "type": "string",
                    "example": "emmmmmmmm"
                }
            }
        },
        "muser.FeedbackParam": {
            "type": "object",
            "required": [
                "describe"
            ],
            "properties": {
                "describe": {
                    "type": "string",
                    "example": "问题描述"
                },
                "phone": {
                    "type": "string",
                    "example": "手机号"
                },
                "pics": {
                    "type": "string",
                    "example": "图片列表"
                },
                "problem": {
                    "type": "string",
                    "example": "遇到的问题"
                }
            }
        },
        "muser.LoginParams": {
            "type": "object",
            "properties": {
                "opToken": {
                    "type": "string",
                    "example": "客户端返回的运营商token"
                },
                "operator": {
                    "type": "string",
                    "example": "客户端返回的运营商，CMCC:中国移动通信, CUCC:中国联通通讯, CTCC:中国电信"
                },
                "platform": {
                    "type": "integer",
                    "example": 0
                },
                "token": {
                    "type": "string",
                    "example": "客户端token"
                }
            }
        },
        "muser.QQLoginParams": {
            "type": "object",
            "properties": {
                "access_token": {
                    "type": "string",
                    "example": "授权token"
                },
                "openid": {
                    "type": "string"
                },
                "platform": {
                    "type": "string",
                    "example": "qzone、pengyou或qplus"
                }
            }
        },
        "muser.UserInfoResp": {
            "type": "object",
            "properties": {
                "age": {
                    "type": "integer",
                    "example": 27
                },
                "avatar": {
                    "type": "string",
                    "example": "头像地址"
                },
                "background_img": {
                    "type": "string",
                    "example": "背景图"
                },
                "born": {
                    "type": "string",
                    "example": "出生日期"
                },
                "country": {
                    "type": "integer",
                    "example": 0
                },
                "gender": {
                    "type": "integer",
                    "example": 0
                },
                "is_anchor": {
                    "type": "integer",
                    "example": 0
                },
                "mobileNum": {
                    "type": "integer",
                    "example": 13177656222
                },
                "nickname": {
                    "type": "string",
                    "example": "昵称 陈二狗"
                },
                "signature": {
                    "type": "string",
                    "example": "个性签名"
                },
                "status": {
                    "type": "integer",
                    "example": 0
                },
                "user_id": {
                    "type": "string",
                    "example": "2009011314521111"
                },
                "user_type": {
                    "type": "integer",
                    "example": 0
                }
            }
        },
        "muser.WeiboLoginParams": {
            "type": "object",
            "required": [
                "access_token",
                "uid"
            ],
            "properties": {
                "access_token": {
                    "type": "string",
                    "example": "通行token"
                },
                "uid": {
                    "type": "integer"
                }
            }
        },
        "muser.WxLoginParam": {
            "type": "object",
            "required": [
                "code"
            ],
            "properties": {
                "code": {
                    "type": "string",
                    "example": "code码"
                }
            }
        },
        "mvideo.DeleteHistoryParam": {
            "type": "object",
            "required": [
                "composeIds"
            ],
            "properties": {
                "composeIds": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                }
            }
        },
        "mvideo.DeletePublishParam": {
            "type": "object",
            "required": [
                "composeIds"
            ],
            "properties": {
                "composeIds": {
                    "type": "string"
                }
            }
        },
        "mvideo.PublishVideosInfo": {
            "type": "object",
            "properties": {
                "browse_num": {
                    "type": "integer"
                },
                "comment_num": {
                    "type": "integer"
                },
                "cover": {
                    "type": "string"
                },
                "create_at": {
                    "type": "integer"
                },
                "describe": {
                    "type": "string"
                },
                "fabulous_num": {
                    "type": "integer"
                },
                "is_recommend": {
                    "type": "integer"
                },
                "is_top": {
                    "type": "integer"
                },
                "share_num": {
                    "type": "integer"
                },
                "status": {
                    "type": "integer"
                },
                "title": {
                    "type": "string"
                },
                "video_addr": {
                    "type": "string"
                },
                "video_duration": {
                    "type": "integer"
                },
                "video_height": {
                    "type": "integer"
                },
                "video_id": {
                    "type": "integer"
                },
                "video_width": {
                    "type": "integer"
                }
            }
        },
        "mvideo.VideoPublishParams": {
            "type": "object",
            "required": [
                "cover",
                "describe",
                "title",
                "videoAddr",
                "videoDuration",
                "videoLabels"
            ],
            "properties": {
                "cover": {
                    "type": "string"
                },
                "describe": {
                    "type": "string"
                },
                "title": {
                    "type": "string"
                },
                "videoAddr": {
                    "type": "string"
                },
                "videoDuration": {
                    "type": "integer"
                },
                "videoLabels": {
                    "type": "string"
                }
            }
        },
        "mvideo.VideosInfoResp": {
            "type": "object",
            "properties": {
                "avatar": {
                    "type": "string"
                },
                "collectAt": {
                    "type": "integer"
                },
                "cover": {
                    "type": "string"
                },
                "createAt": {
                    "type": "integer"
                },
                "describe": {
                    "type": "string"
                },
                "isAttention": {
                    "type": "integer"
                },
                "isRecommend": {
                    "type": "integer"
                },
                "isTop": {
                    "type": "integer"
                },
                "nickName": {
                    "type": "string"
                },
                "title": {
                    "type": "string"
                },
                "userId": {
                    "type": "string"
                },
                "videoAddr": {
                    "type": "string"
                },
                "videoDuration": {
                    "type": "integer"
                },
                "videoHeight": {
                    "type": "integer"
                },
                "videoId": {
                    "type": "integer"
                },
                "videoWidth": {
                    "type": "integer"
                }
            }
        },
        "swag.LoginSwag": {
            "type": "object",
            "properties": {
                "token": {
                    "description": "token",
                    "type": "string"
                },
                "user": {
                    "description": "用户信息",
                    "type": "object",
                    "$ref": "#/definitions/swag.User"
                }
            }
        },
        "swag.User": {
            "type": "object",
            "properties": {
                "age": {
                    "type": "integer"
                },
                "avatar": {
                    "type": "string"
                },
                "background_img": {
                    "type": "string"
                },
                "born": {
                    "type": "string"
                },
                "channel_id": {
                    "type": "integer"
                },
                "city": {
                    "type": "string"
                },
                "create_at": {
                    "type": "integer"
                },
                "device_type": {
                    "type": "integer"
                },
                "gender": {
                    "type": "integer"
                },
                "id": {
                    "type": "integer"
                },
                "is_anchor": {
                    "type": "integer"
                },
                "last_login_time": {
                    "type": "integer"
                },
                "mobile_num": {
                    "type": "integer"
                },
                "nick_name": {
                    "type": "string"
                },
                "password": {
                    "type": "string"
                },
                "signature": {
                    "type": "string"
                },
                "status": {
                    "type": "integer"
                },
                "title": {
                    "type": "string"
                },
                "update_at": {
                    "type": "integer"
                },
                "user_id": {
                    "type": "string"
                }
            }
        }
    }
}`

type swaggerInfo struct {
	Version     string
	Host        string
	BasePath    string
	Schemes     []string
	Title       string
	Description string
}

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = swaggerInfo{
	Version:     "1.0",
	Host:        "",
	BasePath:    "",
	Schemes:     []string{},
	Title:       "FPV电竞APP（应用服）",
	Description: "### 一、公共参数说明（此栏参数均为Headers请求头传递）\n| 参数名 | 说明 | 示例 |\n| ------ | :----- | :----- |\n| AppId | AppId(区分Android,iOS,web) | 5EesXF1i |\n| Secret | 服务端下发的secret 通过/api/v1/client/init接口获取 调用该接口时无需传 且 不参与签名 | DnaukFwVILpcewX6 |\n| Timestamp | 请求时间戳 单位：秒 | 1588888888 |\n| Sign | 签名 | 签名 md5签名32位值 |\n| Version | 当前版本 | 1.0.1 |\n### 二、请求体说明（此栏参数均为POST JSON传递，不可用form-data提交）\n\n{\n'mobileNum': '13177656222',\n'platform': 0\n}\n### 三、接口签名生成方式\n签名加密示例:\nparams = 请求的url路径(不包含域名与参数) + & + Header头参数以`&`拼接（无需按照字典序，具体看以下栗子） + & + appKey\nappKey由服务端下发 并进行保存\nsign = md5(params) 取md5 32位小写\n如：md5(/api/v1/user/mobile/login&AppId=5EesXF1i&Timestamp=1588888888&Version=1.0.1&Secret=DnaukFwVILpcewX6&RfhHecN9zsNcy19Y)\nappKey为RfhHecN9zsNcy19Y\n### 四、API错误码文档\n[点击查看](/api/v1/doc)\n### 五、HTTP状态码说明\n| 状态码 | 说明 |\n| ------ | :----- |\n| 200 | 操作成功 |\n| 400 | 参数错误 |\n| 500 | 内部错误 |",
}

type s struct{}

func (s *s) ReadDoc() string {
	sInfo := SwaggerInfo
	sInfo.Description = strings.Replace(sInfo.Description, "\n", "\\n", -1)

	t, err := template.New("swagger_info").Funcs(template.FuncMap{
		"marshal": func(v interface{}) string {
			a, _ := json.Marshal(v)
			return string(a)
		},
	}).Parse(doc)
	if err != nil {
		return doc
	}

	var tpl bytes.Buffer
	if err := t.Execute(&tpl, sInfo); err != nil {
		return doc
	}

	return tpl.String()
}

func init() {
	swag.Register(swag.Name, &s{})
}
