definitions:
  muser.LoginParams:
    properties:
      opToken:
        example: 客户端返回的运营商token
        type: string
      operator:
        example: 客户端返回的运营商，CMCC:中国移动通信, CUCC:中国联通通讯, CTCC:中国电信
        type: string
      platform:
        example: 0
        type: integer
      token:
        example: 客户端token
        type: string
    type: object
  muser.QQLoginParams:
    properties:
      access_token:
        example: 授权token
        type: string
      openid:
        type: string
      platform:
        example: qzone、pengyou或qplus
        type: string
    type: object
  muser.WeiboLoginParams:
    properties:
      access_token:
        example: 通行token
        type: string
      uid:
        type: integer
    required:
    - access_token
    - uid
    type: object
  muser.WxLoginParam:
    properties:
      code:
        example: code码
        type: string
    required:
    - code
    type: object
  swag.LoginSwag:
    properties:
      token:
        description: token
        type: string
      user:
        $ref: '#/definitions/swag.User'
        description: 用户信息
        type: object
    type: object
  swag.User:
    properties:
      age:
        type: integer
      avatar:
        type: string
      background_img:
        type: string
      born:
        type: string
      channel_id:
        type: integer
      city:
        type: string
      create_at:
        type: integer
      device_type:
        type: integer
      gender:
        type: integer
      id:
        type: integer
      is_anchor:
        type: integer
      last_login_time:
        type: integer
      mobile_num:
        type: integer
      nick_name:
        type: string
      password:
        type: string
      signature:
        type: string
      status:
        type: integer
      title:
        type: string
      update_at:
        type: integer
      user_id:
        type: string
    type: object
info:
  contact: {}
  description: |-
    ### 一、公共参数说明（此栏参数均为Headers请求头传递）
    | 参数名 | 说明 | 示例 |
    | ------ | :----- | :----- |
    | User-Agent | 用户代理 | android |
    | Version | 当前版本 | 1.0.1 |
    ### 二、请求体说明（此栏参数均为POST JSON传递，不可用form-data提交）

    {
    'mobileNum': '13177656222',
    'platform': 0
    }
    ### 三、API错误码文档
    [点击查看](/api/v1/doc)
    ### 四、HTTP状态码说明
    | 状态码 | 说明 |
    | ------ | :----- |
    | 200 | 操作成功 |
    | 400 | 参数错误 |
    | 500 | 内部错误 |
  license: {}
  title: FPV电竞APP（应用服）
  version: "1.0"
paths:
  /api/v1/user/mobile/login:
    post:
      consumes:
      - application/json
      parameters:
      - default: android
        description: android
        in: header
        name: User-Agent
        required: true
        type: string
      - default: 1.0.0
        description: 版本
        in: header
        name: Version
        required: true
        type: string
      - description: 手机号登陆/注册 请求参数
        in: body
        name: LoginParams
        required: true
        schema:
          $ref: '#/definitions/muser.LoginParams'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/swag.LoginSwag'
        "500":
          description: '{"code":500,"data":{},"msg":"fail","tm":"1588888888"}'
          schema:
            type: string
      summary: 手机一键注册/登陆 (ok)
      tags:
      - 001 手机一键注册/登陆 2020-09-10
  /api/v1/user/qq/login:
    post:
      consumes:
      - application/json
      parameters:
      - default: android
        description: android
        in: header
        name: User-Agent
        required: true
        type: string
      - default: 1.0.0
        description: 版本
        in: header
        name: Version
        required: true
        type: string
      - description: QQ登陆/注册 请求参数
        in: body
        name: WeiboLoginParams
        required: true
        schema:
          $ref: '#/definitions/muser.QQLoginParams'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/swag.LoginSwag'
        "500":
          description: '{"code":500,"data":{},"msg":"fail","tm":"1588888888"}'
          schema:
            type: string
      summary: QQ注册/登陆 (ok)
      tags:
      - 004 QQ注册/登陆 2020-09-14
  /api/v1/user/wechat/login:
    post:
      consumes:
      - application/json
      parameters:
      - default: android
        description: android
        in: header
        name: User-Agent
        required: true
        type: string
      - default: 1.0.0
        description: 版本
        in: header
        name: Version
        required: true
        type: string
      - description: 微信登陆/注册 请求参数
        in: body
        name: WxLoginParam
        required: true
        schema:
          $ref: '#/definitions/muser.WxLoginParam'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/swag.LoginSwag'
        "500":
          description: '{"code":500,"data":{},"msg":"fail","tm":"1588888888"}'
          schema:
            type: string
      summary: 微信注册/登陆 (ok)
      tags:
      - 002 微信注册/登陆 2020-09-11
  /api/v1/user/weibo/login:
    post:
      consumes:
      - application/json
      parameters:
      - default: android
        description: android
        in: header
        name: User-Agent
        required: true
        type: string
      - default: 1.0.0
        description: 版本
        in: header
        name: Version
        required: true
        type: string
      - description: 微博登陆/注册 请求参数
        in: body
        name: WeiboLoginParams
        required: true
        schema:
          $ref: '#/definitions/muser.WeiboLoginParams'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/swag.LoginSwag'
        "500":
          description: '{"code":500,"data":{},"msg":"fail","tm":"1588888888"}'
          schema:
            type: string
      summary: 微博注册/登陆 (ok)
      tags:
      - 003 微博注册/登陆 2020-09-11
swagger: "2.0"
