public_addr: :11010
mysql:
  main:
    master: root:a3202381@tcp(127.0.0.1:3306)/fpv?charset=utf8mb4
    slave:
      - root:a3202381@tcp(127.0.0.1:3306)/fpv?charset=utf8mb4
      - root:a3202381@tcp(127.0.0.1:3306)/fpv?charset=utf8mb4
      - root:a3202381@tcp(127.0.0.1:3306)/fpv?charset=utf8mb4
    max_idle: 128
    max_active: 128

redis:
  main:
    master:
      ip: 127.0.0.1
      port: 6379

    slave:
      - ip: 127.0.0.1
        port: 6379

    dboption:
      - dbid: 0
        name:
        max_idle: 128
        max_active: 128

## 日志等级 0 debug 1 info 2 warn 3 error
log:
  dir: ./log/app_server.log
  level: 0
  show_color: true

debug: true
