publicAddr: :11001
pprofAddr: :12001
mode: dev
mysql:
  main:
    master: root:bluetrans888@tcp(192.168.5.12:3306)/sports_service?charset=utf8mb4
    slave:
      - root:bluetrans888@tcp(192.168.5.12:3306)/sports_service?charset=utf8mb4
      - root:bluetrans888@tcp(192.168.5.12:3306)/sports_service?charset=utf8mb4
      - root:bluetrans888@tcp(192.168.5.12:3306)/sports_service?charset=utf8mb4
    maxIdle: 128
    maxActive: 128
  venue:
    master: root:bluetrans888@tcp(192.168.5.12:3306)/venue?charset=utf8mb4
    slave:
      - root:bluetrans888@tcp(192.168.5.12:3306)/venue?charset=utf8mb4
      - root:bluetrans888@tcp(192.168.5.12:3306)/venue?charset=utf8mb4
      - root:bluetrans888@tcp(192.168.5.12:3306)/venue?charset=utf8mb4
    maxIdle: 128
    maxActive: 128
redis:
  main:
    master:
      ip: 192.168.5.12
      port: 6378

    slave:
      - ip: 192.168.5.12
        port: 6378

    dboption:
      - dbid: 0
        name:
        maxIdle: 128
        maxActive: 128
redisPassword:

## 开放平台appid
wechatAppid: wx9306bf43be47830b
## 开放平台secret
wechatSecret: 3af44d06170ecdab4b49d1c70268c71f
nsqAddr: 127.0.0.1:4150
amqpDsn: amqp://admin:admin@127.0.0.1:5672
staticDomain: http://fpv-web-qa.youzu.com
## 微信支付 回调地址
wechatNotifyUrl: http://fpv-app-api-qa.bluetrans.cn/api/v1/pay/wechat/notify
## 微信退款回调地址
wechatRefundNotify: http://fpv-app-api-qa.bluetrans.cn/api/v1/pay/wechat/refund
## 支付宝 回调地址
alipayNotifyUrl: http://fpv-app-api-qa.bluetrans.cn/api/v1/pay/alipay/notify
# 苹果
appleLinkPath: /data/service/fpv-app-api/config
# 微信证书
certFilePath: /data/service/fpv-app-api/config
keyFilePath: /data/service/fpv-app-api/config
pkcs12FilePath: /data/service/fpv-app-api/config
## 日志等级 0 debug 1 info 2 warn 3 error
log:
  path: ./log/app_server_%s.log
  level: 0
  showColor: false

debug: true
