publicAddr: :9001
pprofAddr: :12001
mode: prod
mysql:
  main:
    master: fpv_app_api:KOGDHjAgk2tho1sq@tcp(10.5.0.235:35706)/fpv-app-api?charset=utf8mb4
    slave:
      - fpv_app_api:KOGDHjAgk2tho1sq@tcp(10.5.0.235:35706)/fpv-app-api?charset=utf8mb4
      - fpv_app_api:KOGDHjAgk2tho1sq@tcp(10.5.0.235:35706)/fpv-app-api?charset=utf8mb4
      - fpv_app_api:KOGDHjAgk2tho1sq@tcp(10.5.0.235:35706)/fpv-app-api?charset=utf8mb4
    maxIdle: 128
    maxActive: 128
    logPath: /data/logs/fpv-app-api/db/db_fpv_%s.log
  venue:
    master: venue:4QutVx9oZ7Gq5Xwl@tcp(10.5.0.235:35706)/venue?charset=utf8mb4
    slave:
      - venue:4QutVx9oZ7Gq5Xwl@tcp(10.5.0.235:35706)/venue?charset=utf8mb4
      - venue:4QutVx9oZ7Gq5Xwl@tcp(10.5.0.235:35706)/venue?charset=utf8mb4
      - venue:4QutVx9oZ7Gq5Xwl@tcp(10.5.0.235:35706)/venue?charset=utf8mb4
    maxIdle: 128
    maxActive: 128
    logPath: /data/logs/fpv-app-api/db/db_venue_%s.log
redis:
  main:
    master:
      #ip: 10.6.1.111
      #ip: 192.168.0.218
      ip: 10.5.0.88
      port: 6379

    slave:
      #- ip: 10.6.1.111
      - ip: 10.5.0.88
        port: 6379

    dboption:
      - dbid: 0
        name:
        maxIdle: 128
        maxActive: 128
#redisPassword: eiMWaYbnNvT7sr5k
redisPassword: yN1MnL8O7DfS3aBh
amqpDsn: amqp://admin:admin@127.0.0.1:5672
staticDomain: https://fpv-web.bluetrans.cn
## 微信支付 回调地址
wechatNotifyUrl: https://fpv-app-api.bluetrans.cn/api/v1/pay/wechat/notify
## 微信退款回调地址
wechatRefundNotify: https://fpv-app-api.bluetrans.cn/api/v1/pay/wechat/refund
## 支付宝 回调地址
alipayNotifyUrl: https://fpv-app-api.bluetrans.cn/api/v1/pay/alipay/notify
# 苹果
appleLinkPath: /data/service/fpv-app-api/config/apple-app-site-association
# 微信证书
certFilePath: /data/service/fpv-app-api/config/apiclient_cert.pem
keyFilePath: /data/service/fpv-app-api/config/apiclient_key.pem
pkcs12FilePath: /data/service/fpv-app-api/config/apiclient_cert.p12
# 分享地址
shareUrl: https://bluetrans.cn
# 腾讯im SDKAppID
tencentImAppId: 1400576334
# 腾讯im 密钥
tencentImSecret: 080789c06a28b355e1ec94b97ad61edc4eb887275e68fa0046f5659cead396e7
# 腾讯im 管理员
tencentImIdentifier: bluetrans
## 日志等级 0 debug 1 info 2 warn 3 error
log:
  path: /data/logs/fpv-app-api/app_server_%s.log
  level: 0
  showColor: false

debug: false
