publicAddr: :9001
pprofAddr: :12001
mode: prod
mysql:
  main:
    master: fpv-app-api:QbjScl1ms2fKqWIx@tcp(192.168.0.127:3306)/fpv-app-api?charset=utf8mb4
    slave:
      - fpv-app-api:QbjScl1ms2fKqWIx@tcp(192.168.0.127:3306)/fpv-app-api?charset=utf8mb4
      - fpv-app-api:QbjScl1ms2fKqWIx@tcp(192.168.0.127:3306)/fpv-app-api?charset=utf8mb4
      - fpv-app-api:QbjScl1ms2fKqWIx@tcp(192.168.0.127:3306)/fpv-app-api?charset=utf8mb4
    maxIdle: 128
    maxActive: 128
  venue:
    master: fpv-app-api:QbjScl1ms2fKqWIx@tcp(192.168.0.127:3306)/venue?charset=utf8mb4
    slave:
      - fpv-app-api:QbjScl1ms2fKqWIx@tcp(192.168.0.127:3306)/venue?charset=utf8mb4
      - fpv-app-api:QbjScl1ms2fKqWIx@tcp(192.168.0.127:3306)/venue?charset=utf8mb4
      - fpv-app-api:QbjScl1ms2fKqWIx@tcp(192.168.0.127:3306)/venue?charset=utf8mb4
    maxIdle: 128
    maxActive: 128
redis:
  main:
    master:
      ip: 192.168.0.218
      port: 6379

    slave:
      - ip: 192.168.0.218
        port: 6379

    dboption:
      - dbid: 0
        name:
        maxIdle: 128
        maxActive: 128
redisPassword: o6DPVfuCAUwOgrNM
amqpDsn: amqp://admin:admin@127.0.0.1:5672
staticDomain: https://fpv-web.bluetrans.cn
## 微信支付 回调地址
wechatNotifyUrl: https://fpv-app-api.bluetrans.cn/api/v1/pay/wechat/notify
## 微信退款回调地址
wechatRefundNotify: https://fpv-app-api.bluetrans.cn/api/v1/pay/wechat/refund
## 支付宝 回调地址
alipayNotifyUrl: https://fpv-app-api.bluetrans.cn/api/v1/pay/alipay/notify
# 苹果
appleLinkPath: /data/service/fpv-app-api/config
# 微信证书
certFilePath: /data/service/fpv-app-api/config/apiclient_cert.pem
keyFilePath: /data/service/fpv-app-api/config/apiclient_key.pem
pkcs12FilePath: /data/service/fpv-app-api/config/apiclient_cert.p12
## 日志等级 0 debug 1 info 2 warn 3 error
log:
  path: /data/logs/fpv-app-api/app_server_%s.log
  level: 0
  showColor: false

debug: false
