publicAddr: :11001
pprofAddr: :12001
mode: test
mysql:
  main:
    master: root:root@2020@tcp(10.6.176.147:3306)/sports_service?charset=utf8mb4
    slave:
      - root:root@2020@tcp(10.6.176.147:3306)/sports_service?charset=utf8mb4
      - root:root@2020@tcp(10.6.176.147:3306)/sports_service?charset=utf8mb4
      - root:root@2020@tcp(10.6.176.147:3306)/sports_service?charset=utf8mb4
    maxIdle: 128
    maxActive: 128

redis:
  main:
    master:
      ip: 10.6.176.147
      port: 7916

    slave:
      - ip: 10.6.176.147
        port: 7916

    dboption:
      - dbid: 0
        name:
        maxIdle: 128
        maxActive: 128

## 日志等级 0 debug 1 info 2 warn 3 error
log:
  path: ./log/app_server.log
  level: 0
  showColor: true

debug: true
