publicAddr: :9001
pprofAddr: :12001
mode: prod
mysql:
  main:
    master: fpv-app-api:QbjScl1ms2fKqWIx@tcp(192.168.0.127:3306)/fpv-app-api?charset=utf8mb4
    slave:
      - fpv-app-api:QbjScl1ms2fKqWIx@tcp(192.168.0.127:3306)/fpv-app-api?charset=utf8mb4
      - fpv-app-api:QbjScl1ms2fKqWIx@tcp(192.168.0.127:3306)/fpv-app-api?charset=utf8mb4
      - fpv-app-api:QbjScl1ms2fKqWIx@tcp(192.168.0.127:3306)/fpv-app-api?charset=utf8mb4
    maxIdle: 128
    maxActive: 128

redis:
  main:
    master:
      ip: 192.168.0.218
      port: 6379

    slave:
      - ip: 192.168.0.218
        port: 6379

    dboption:
      - dbid: 0
        name:
        maxIdle: 128
        maxActive: 128
redisPassword: o6DPVfuCAUwOgrNM
amqpDsn: amqp://admin:admin@127.0.0.1:5672
staticDomain: http://fpv-web.youzu.com
## 日志等级 0 debug 1 info 2 warn 3 error
log:
  path: /data/logs/fpv-app-api/app_server_%s.log
  level: 0
  showColor: false

debug: false
