publicAddr: :11001
pprofAddr: :12001
mode: dev
mysql:
  main:
    master: root:a3202381@tcp(127.0.0.1:3306)/fpv2?charset=utf8mb4
    slave:
      - root:a3202381@tcp(127.0.0.1:3306)/fpv2?charset=utf8mb4
      - root:a3202381@tcp(127.0.0.1:3306)/fpv2?charset=utf8mb4
      - root:a3202381@tcp(127.0.0.1:3306)/fpv2?charset=utf8mb4
    maxIdle: 128
    maxActive: 128

redis:
  main:
    master:
      ip: 127.0.0.1
      port: 6379

    slave:
      - ip: 127.0.0.1
        port: 6379

    dboption:
      - dbid: 0
        name:
        maxIdle: 128
        maxActive: 128
redisPassword: n8R39KbtEfCEfyIk

## 开放平台appid
wechatAppid: wx9306bf43be47830b
## 开放平台secret
wechatSecret: 3af44d06170ecdab4b49d1c70268c71f
nsqAddr: 127.0.0.1:4150

## 日志等级 0 debug 1 info 2 warn 3 error
log:
  path: ./log/app_server.log
  level: 0
  showColor: true

debug: true
