publicAddr: :11001
pprofAddr: :12001
mode: dev
mysql:
  main:
    master: root:bluetrans888@tcp(10.1.3.12:3306)/sports_service?charset=utf8mb4
    slave:
      - root:bluetrans888@tcp(10.1.3.12:3306)/sports_service?charset=utf8mb4
      - root:bluetrans888@tcp(10.1.3.12:3306)/sports_service?charset=utf8mb4
      - root:bluetrans888@tcp(10.1.3.12:3306)/sports_service?charset=utf8mb4
    maxIdle: 128
    maxActive: 128
  venue:
    master: root:bluetrans888@tcp(10.1.3.12:3306)/venue?charset=utf8mb4
    slave:
      - root:bluetrans888@tcp(10.1.3.12:3306)/venue?charset=utf8mb4
      - root:bluetrans888@tcp(10.1.3.12:3306)/venue?charset=utf8mb4
      - root:bluetrans888@tcp(10.1.3.12:3306)/venue?charset=utf8mb4
    maxIdle: 128
    maxActive: 128
redis:
  main:
    master:
      ip: 10.1.3.12
      port: 6378

    slave:
      - ip: 10.1.3.12
        port: 6378

    dboption:
      - dbid: 0
        name:
        maxIdle: 128
        maxActive: 128
redisPassword:

## 开放平台appid
wechatAppid: wx9306bf43be47830b
## 开放平台secret
wechatSecret: 3af44d06170ecdab4b49d1c70268c71f
nsqAddr: 127.0.0.1:4150
amqpDsn: amqp://admin:admin@127.0.0.1:5672
staticDomain: https://fpv-web-qa.bluetrans.cn
## 微信支付 回调地址
wechatNotifyUrl: http://fpv-app-api-qa.bluetrans.cn/api/v1/pay/wechat/notify
## 微信退款回调地址
wechatRefundNotify: http://fpv-app-api-qa.bluetrans.cn/api/v1/pay/wechat/refund
## 支付宝 回调地址
alipayNotifyUrl: http://fpv-app-api-qa.bluetrans.cn/api/v1/pay/alipay/notify
# 苹果
appleLinkPath: /data/service/fpv-app-api/config/apple-app-site-association
# 微信证书
certFilePath: /data/service/fpv-app-api/config/apiclient_cert.pem
keyFilePath: /data/service/fpv-app-api/config/apiclient_key.pem
pkcs12FilePath: /data/service/fpv-app-api/config/apiclient_cert.p12
# 分享地址
shareUrl: https://bluetrans.cn
## 腾讯im SDKAppID
#tencentImAppId: 1400570443
## 腾讯im 密钥
#tencentImSecret: a6380a7413ed7fdcfac951b9c5fde542c661864c596a4aa7bc1d15c87df5b1f7
# 腾讯im SDKAppID
tencentImAppId: 1400576334
# 腾讯im 密钥
tencentImSecret: 080789c06a28b355e1ec94b97ad61edc4eb887275e68fa0046f5659cead396e7
# 腾讯im 管理员
tencentImIdentifier: bluetrans
## 日志等级 0 debug 1 info 2 warn 3 error
log:
  path: ./log/app_server_%s.log
  level: 0
  showColor: false

debug: true
