definitions:
  swag.LoginParamsSwag:
    properties:
      mobileNum:
        example: 手机号码
        type: string
      platform:
        example: 1
        type: integer
    required:
    - mobileNum
    type: object
  swag.LoginSwag:
    properties:
      token:
        type: string
      user:
        $ref: '#/definitions/swag.User'
        type: object
    type: object
  swag.User:
    properties:
      age:
        type: integer
      avatar:
        type: string
      background_img:
        type: string
      born:
        type: string
      channel_id:
        type: integer
      city:
        type: string
      create_at:
        type: integer
      device_type:
        type: integer
      gender:
        type: integer
      id:
        type: integer
      is_anchor:
        type: integer
      last_login_time:
        type: integer
      mobile_num:
        type: integer
      nick_name:
        type: string
      password:
        type: string
      signature:
        type: string
      status:
        type: integer
      title:
        type: string
      update_at:
        type: integer
      user_id:
        type: string
    type: object
  swag.WxLoginSwag:
    properties:
      code:
        example: 授权码
        type: string
    required:
    - code
    type: object
info:
  contact: {}
  description: '### API错误码文档 [点击查看](/api/v1/doc)'
  license: {}
  title: FPV电竞app(登陆服)
  version: "1.0"
paths:
  /api/v1/user/mobile/login:
    post:
      consumes:
      - application/json
      parameters:
      - default: android
        description: android
        in: header
        name: User-Agent
        required: true
        type: string
      - default: 1.0.0
        description: 版本
        in: header
        name: Version
        required: true
        type: string
      - description: 手机号登陆/注册 请求参数
        in: body
        name: LoginParams
        required: true
        schema:
          $ref: '#/definitions/swag.LoginParamsSwag'
          type: object
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/swag.LoginSwag'
            type: object
        "500":
          description: '{"code":500,"data":{},"msg":"fail","tm":"1588888888"}'
          schema:
            type: string
      summary: 手机一键注册/登陆 (ok)
      tags:
      - 001 手机一键注册/登陆 2020-09-10
  /api/v1/user/wechat/login:
    post:
      consumes:
      - application/json
      parameters:
      - default: android
        description: android
        in: header
        name: User-Agent
        required: true
        type: string
      - default: 1.0.0
        description: 版本
        in: header
        name: Version
        required: true
        type: string
      - description: 微信登陆/注册 请求参数
        in: body
        name: WxLoginParam
        required: true
        schema:
          $ref: '#/definitions/swag.WxLoginSwag'
          type: object
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/swag.LoginSwag'
            type: object
        "500":
          description: '{"code":500,"data":{},"msg":"fail","tm":"1588888888"}'
          schema:
            type: string
      summary: 微信注册/登陆 (ok)
      tags:
      - 002 微信注册/登陆 2020-09-11
swagger: "2.0"
