publicAddr: :15001
pprofAddr: :14001
mode: dev
## 日志等级 0 debug 1 info 2 warn 3 error
log:
  path: ./log/barrage_server.log
  level: 0
  showColor: true
nsqAddr: 127.0.0.1:4150
maxMsgCacheLen: 10000
kafkaAddr: 10.6.30.199:9092
kafkaTopic: test1

redis:
  main:
    master:
      ip: 127.0.0.1
      port: 6379

    slave:
      - ip: 127.0.0.1
        port: 6379

    dboption:
      - dbid: 0
        name:
        maxIdle: 128
        maxActive: 128

debug: true
