publicAddr: :15001
pprofAddr: :14001
mode: dev
## 日志等级 0 debug 1 info 2 warn 3 error
log:
  path: ./log/barrage_server_%s.log
  level: 0
  showColor: true
nsqAddr: 127.0.0.1:4150
maxMsgCacheLen: 10000
kafkaAddr: 10.6.30.199:9092
kafkaTopic: test1
mysql:
  main:
    master: root:bluetrans888@tcp(192.168.5.12:3306)/sports_service?charset=utf8mb4
    slave:
      - root:bluetrans888@tcp(192.168.5.12:3306)/sports_service?charset=utf8mb4
      - root:bluetrans888@tcp(192.168.5.12:3306)/sports_service?charset=utf8mb4
      - root:bluetrans888@tcp(192.168.5.12:3306)/sports_service?charset=utf8mb4
    maxIdle: 128
    maxActive: 128

redis:
  main:
    master:
      ip: 192.168.5.12
      port: 6378

    slave:
      - ip: 192.168.5.12
        port: 6378

    dboption:
      - dbid: 0
        name:
        maxIdle: 128
        maxActive: 128
redisPassword:

debug: true
